CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    username VARCHAR(100) UNIQUE NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    password TEXT NOT NULL,
    preference VARCHAR(50) DEFAULT 'stock',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);